# Config file for labeler to auto label PRs
documentation:
  - README.md
  - docs/**/*

UI/UX:
  - '**/*.css'
  - '**/*.html'

automation:
  - .github/**/*.yml
  - .eslintrc.json

npm packages:
  - '**/package.json'
  - '**/package-lock.json'

build:
  - build/*
  - build/**/*

components:
  - src/components/**/*.js

pages:
  - src/pages/**/*.js
